### ISSUE TITLE
Minio logs are not coming 

### ISSUE THREAD

**Issue by sachinar** [heptio/ark#871] opened 2018-09-25 12:45 UTC
Hi Team,

@ncdc @skriss I tried minio deployment for local backup.
I want logs of my backup & restore.

when I do `ark backup logs <backup-name>`

i am getting this error,
`An error occurred: Get http://minio:9000/ark/namespacebackup/namespacebackup-logs.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%!F(MISSING)20180925%!F(MISSING)minio%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20180925T124422Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=d45fdf704202cdc35917152203ad94e0c8cfdf972aacf7737777b5a7dd4da372: dial tcp: lookup minio on 8.8.8.8:53: no such host`

This error for restore logs also. How I will get logs ?

**Comment by ncdc** [comment] 2018-09-27 20:29
@sachinar this is a duplicate of #387. Please try the suggestions there. If they work, you could be willing to submit a docs PR?

**Closed by ncdc** 2018-09-27 20:29 UTC
Labels: Duplicate

**Comment by sachinar** [comment] 2018-10-05 10:27
@ncdc I tried but it didn't worked. It is showing same error.
