### ISSUE TITLE
Support backing up to a folder in object storage

### ISSUE THREAD

**Issue by badbeeker** [heptio/ark#543] opened 2018-06-11 19:39 UTC
Hello,

Nothing is listed in the documentation, but I was wondering if you can use a folder in an existing s3 bucket as a storage option instead of just the bucket name?

For example:
- heptio-ark-backups
  - cluster1
    - backup1
    - backup2
  - cluster2
    - backup1
  - cluster3
    - backup1

If so, would the configuration be:
```
backupStorageProvider:
  name: aws
  bucket: heptio-ark-backups/cluster1
  config:
    region: us-west-2
```

**Comment by ncdc** [comment] 2018-06-11 19:41
Hi @badbeeker, thanks for your question. We will be adding support for this soon-ish. I have a WIP PR just to see what it would look like at #515. We're working on prioritizing our backlog and will have an updated ETA soon (sorry I can't be more specific right now!).

**Comment by ncdc** [comment] 2018-06-11 19:42
This is actually a duplicate of #167, so I'm going to close it. Please watch that issue for updates!

**Closed** 2018-06-11 19:43 UTC
Labels: Duplicate

**Comment by badbeeker** [comment] 2018-06-11 21:39
Thanks @ncdc, I'll continue to watch that ticket.
