### ISSUE TITLE
Support for swift backend 

### ISSUE THREAD

**Issue by neith00** [heptio/ark#528] opened 2018-06-05 20:01 UTC
Would be nice if ark could use OpenStack's swift backend.

**Comment by ncdc** [comment] 2018-06-05 20:09
@neith00 thanks for your suggestion. This is a duplicate of #119. We are not adding new backends in-tree, but Ark has a plugin model exactly for this use case. I believe someone is working on an external plugin for it. I've just sent off an email to check on the status. I'm going to close this, and as soon as I get some information about the plugin, we'll make sure to link to it from Ark's documentation.

**Closed by ncdc** 2018-06-05 20:09 UTC
Labels: Duplicate
