### ISSUE TITLE
Supporting cross region restore.

### ISSUE THREAD

**Issue by alemco** [heptio/ark#194] opened 2017-11-09 14:56 UTC
To do a restore in a different region some steps have to be done manually:

1. Copy the pv snapshots from current region to destination region.
2. Downloaded the backup files and modify the "ark-backup.json" file and change the snapshot-id to match the id of the destination and change the source region to destination region.
3. un-tar the backup tar"backup.tar.gz" file and modify region and zone in each "resource/persistentvolumes/<pv-name>" to match the destination region and zone.
4. zip the un-tar'd files and upload all the downloaded files to the S3 bucket in the destination region

It will be great to automate some of that to support cross region restore.

**Comment by ncdc** [comment] 2017-11-09 15:00
This could maybe be something like `ark backup migrate --to-region=r --to-zone=z`. Will definitely need to think through what knobs we need and how to make it as easy as possible for the user.

This also looks similar in part to #103, now that it jogged my memory.

**Comment by ncdc** [comment] 2017-11-13 20:53
I'm going to close this as a dupe of #103, and we'll continue to brainstorming there. Thanks!

**Closed by ncdc** 2017-11-13 20:53 UTC
