### ISSUE TITLE
Cross Cluster Backup and Restore problem with Rook PVs

### ISSUE THREAD

**Issue by pms1969** [heptio/ark#556] opened 2018-06-15 07:08 UTC
Following on from the conversation on slack ([here](https://kubernetes.slack.com/archives/C6VCGP4MT/p1528970160000010), [here](https://kubernetes.slack.com/archives/C6VCGP4MT/p1528991008000695), [here](https://kubernetes.slack.com/archives/C6VCGP4MT/p1528996413000638) and [here](https://kubernetes.slack.com/archives/C6VCGP4MT/p1528999063000291));

The 10k foot view is that I have a cluster with Rook volumes in a couple of namespaces.  I'd need to update the cluster, so have created a new cluster beside it with the appropriate changes (AWS deployed, self managed, not EKS), and I need to migrate the rook volumes and state in 2 namespaces to the other cluster.  

Ark works wonderfully for everything except the Rook PVs.  And while I'm at it, let me thank you for creating Ark.  I spent a few days researching ways to backup and restore cluster state, and for me at least, Ark is a clear winner.

What I tried: 
* [The Ark Rook plugin](https://github.com/stevesloka/ark-blockstore-rook).
  This looked to work (as in there were no errors), but PV data wasn't restored.  [On closer inspection](https://github.com/stevesloka/ark-blockstore-rook/issues/2) the data was never persisted to S3, but snapshots were created on the rook-api pod.  I don't currently have a way of getting the snapshots into and out of S3.
* @ncdc then pointed me to the new Restic daemonset in 0.9.0-alpha-2.  
  I gave this a shot, and it works fine (I've got a backup, will check restore today) for PV's attached to active pods.  The trip up came when I discovered that one of our deployments maintains state in PV's for transient pods.  The pods come and go when people log in to and out of an application ([JuypyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html)).  So at any given time, none of the PV's may be attached to a pod, making backup with Restic impossible.

And that's where I'm at.

Looking around I discovered [backy2](http://backy2.com/docs/index.html), so perhaps this in conjunction with the Ark Rook plugin may be successful.  I'll let you know if I have any luck.  Any other suggestions gratefully welcomed.

**Comment by ncdc** [comment] 2018-06-19 14:58
@skriss could you please assist?

**Comment by skriss** [comment] 2018-06-19 15:51
@pms1969 could you provide the output of `ark restore logs prod-tools4-20180615165209`? Thanks!

**Comment by ncdc** [comment] 2018-06-21 11:13
Are any of the volumes you're trying to back up with restic hostPath?

**Comment by pms1969** [comment] 2018-06-21 11:57
@ncdc not sure what that means :(

There are a few, but the one in question is created via the [mongodb helm chart](https://github.com/kubernetes/charts/tree/master/stable/mongodb)

**Comment by ncdc** [comment] 2018-06-21 13:30
Ok, so the volumes you'd specified in the `backup.ark.heptio.com/backup-volumes` pod annotation are all Rook PVCs?

**Comment by pms1969** [comment] 2018-06-21 15:16
Yes

**Comment by skriss** [comment] 2018-06-21 18:35
@pms1969 I was able to reproduce this issue and I see what the problem is.  During restore, Ark is not properly waiting for the PV/PVC to be created and mounted before attempting to restore the contents of the volume using restic. I'll start working on a fix for this and hope to get it out to you ASAP.  Thanks for testing and reporting!!

**Comment by pms1969** [comment] 2018-06-22 06:43
@skriss no, no..  Thank you.

**Comment by rosskukulinski** [comment] 2018-06-24 23:11
@skriss adding to the v0.9.0 milestone, please let me know if that doesn't seem right to you.

**Comment by skriss** [comment] 2018-06-25 22:13
@rosskukulinski yes. there were actually a few issues at play here but all should be resolved with the next alpha/beta.

**Comment by skriss** [comment] 2018-06-27 21:20
The issues that were at play here *should* all be resolved now in master, so I'm going to close this issue out, but feel free to reopen or open a new one as needed. We should be putting out a new tagged alpha/beta shortly for testing!

**Closed by skriss** 2018-06-27 21:20 UTC
Labels: Bug, P1 - Important
