### ISSUE TITLE
Ark unable to restore PV/PVC from GCP snapshots

### ISSUE THREAD

**Issue by agusl88** [heptio/ark#921] opened 2018-10-10 19:37 UTC
**What steps did you take and what happened:**

1 - Schedule a backup for the different namespaces of my GKE Cluster
2 - Recreated the cluster (i was needed in order to tune some settings that can´t be changed on an existing cluster, at least terraform can´t do it with a destroy/create)
3 - Installed ark in the new cluster, same version/settings than before with `restoreOnlyMode: true`
4 - Attempted to restore the backups using `ark restore create --from-backup`

**What did you expect to happen:**

All deployments/services/etc where restored, but some of the PVC failed

```
ark restore describe monitoring-20181010142353-20181010162853
Name:         monitoring-20181010142353-20181010162853
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  monitoring-20181010142353

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:
  Ark:        <none>
  Cluster:    <none>
  Namespaces:
    monitoring:  not restored: replicasets.apps "grafana-547686c94f" already exists and is different from backed up version.
                 not restored: replicasets.apps "kube-state-metrics-7cd9c448b7" already exists and is different from backed up version.
                 not restored: replicasets.apps "prometheus-operator-586865c679" already exists and is different from backed up version.
                 not restored: replicasets.apps "stackdriver-exporter-6cdd796d" already exists and is different from backed up version.

Errors:
  Ark:        <none>
  Cluster:  error executing PVAction for /tmp/138742704/resources/persistentvolumes/cluster/pvc-0d9dd688-95d1-11e8-8d9a-42010a8e002d.json: timeout reached waiting for volume restore-147a1b68-3f92-4575-ac5c-687b0d18bdc5 to be ready
            error executing PVAction for /tmp/138742704/resources/persistentvolumes/cluster/pvc-f5a90019-95d0-11e8-8d9a-42010a8e002d.json: timeout reached waiting for volume restore-9e60e21e-640c-4648-af41-7596f008b415 to be ready
  Namespaces: <none>
```

And this is how the persistent volumes and disk look now on GCP

<img width="874" alt="captura de pantalla 2018-10-10 a la s 16 38 51" src="https://user-images.githubusercontent.com/4117991/46761521-13e44100-ccab-11e8-8303-9d3f4751b76a.png">

![captura de pantalla 2018-10-10 a la s 16 32 55](https://user-images.githubusercontent.com/4117991/46761284-75f07680-ccaa-11e8-98d4-9f7ae67f780e.png)

**Environment:**

- Ark version (use `ark version`):   0.9.7
- Kubernetes version (use `kubectl version`): v1.10.7
- Kubernetes installer & version: v1.10.6-gke.4
- Cloud provider or hardware configuration: GKE

**Comment by ncdc** [comment] 2018-10-10 19:40
Hi @agusl88, if I'm reading this correctly, this is a duplicate of #282, which we have fixed in our master development branch. The fix will be out in v0.10.0, due out later this month or early November. We may be able to backport it to a 0.9.x bugfix release, depending on the complexity of the patch.

**Comment by agusl88** [comment] 2018-10-10 19:49
yes, it looks like a duplicate. The smaller volumes (1/2gb) didn´t had any problems, but the 43gb volumes that are taking a bit more to restore are triggering the 30s timeout described on #282

**Comment by ncdc** [comment] 2018-10-10 19:50
@skriss you ok with a simple fix for this (gut SnapshotService in release-0.9) for our October 18 0.9.x bug fix release?

**Comment by skriss** [comment] 2018-10-10 21:31
sure

**Closed** 2018-10-17 14:29 UTC
Labels: Duplicate
