### ISSUE TITLE
error="no Items field in &v1.Status{TypeMeta:v1.TypeMeta{Kind:\"Status\", APIVersion:\"v1\"}, 

### ISSUE THREAD

**Issue by debianmaster** [heptio/ark#525] opened 2018-06-02 13:48 UTC
This is on openshift 3.9 . (i.e.  k8s 1.9) 
using ark readme.
```sh
ark backup create nginx-backup --selector app=nginx
```

When attempting a backup i see following error in ark pod.
```
time="2018-06-02T13:36:21Z" level=error msg="backup failed" error="no Items field in &v1.Status{TypeMeta:v1.TypeMeta{Kind:\"Status\", APIVersion:\"v1\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\"}, Status:\"Success\", Message:\"\", Reason:\"\", Details:(*v1.StatusDetails)(nil), Code:0}" key=heptio-ark/nginx-backup logSource="pkg/controller/backup_controller.go:273"

```

Also backup failed with following status

```
$ ark backup describe nginx-backup
Name:         nginx-backup
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Phase:  Failed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=nginx

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Expiration:  2018-07-02 21:36:12 +0800 +08

Validation errors:  <none>

Persistent Volumes: <none included>```

**Comment by ncdc** [comment] 2018-06-02 18:05
Hi @debianmaster, thanks for the report. This is actually a duplicate of #475, which we've fixed in our master branch. Our next release, v0.9.0, will have the fix. We anticipate releasing it this month (June).

**Closed by ncdc** 2018-06-02 18:05 UTC
Labels: Duplicate
