### ISSUE TITLE
Restore of restic backups does not work

### ISSUE THREAD

**Issue by bashofmann** [heptio/ark#838] opened 2018-09-11 14:52 UTC
**What steps did you take and what happened:**
If I follow the restic guide at https://github.com/heptio/ark/blob/master/docs/restic.md the data of the volume is successfully backed up, but never restored.

The ark backup is created successfully, the PodVolumeBackupResource is successfully created, and in S3 you can also see the created restic backups in the restic bucket.

If you download the backup though, the `snapshot.ark.heptio.com/` annotation that should be added by the backup to the pod metadata is missing.

By adding further logging, I can see that the `SetPodSnapshotAnnotation` method is definitely called with a valid snapshot id, but the `itemBytes` that are written to the tar archive (https://github.com/heptio/ark/blob/1c26fbde320a2f192d712af8710bfac3d6f4e4f3/pkg/backup/item_backupper.go#L258), do not contain this annotation, which as far as I can see results in ark, never trying to restore the volume with restic.

The bug was likely introduced with https://github.com/heptio/ark/commit/11c176c490bbe00d21a2260f96192a3a1af21388 and the updated `metadata` is never written back to the `obj` that is persisted.

**What did you expect to happen:**
When you restore a backup with restic the data of the volume should be restored.

**Environment:**

- Ark version (use `ark version`):  tested in 0.9.3 and master
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: OpenStack with Quobyte S3
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by ncdc** [comment] 2018-09-11 14:59
@bashofmann thanks for the report. This is a duplicate of #822, and we have a fix pending in #834.

**Comment by bashofmann** [comment] 2018-09-11 15:00
Awesome, thanks and sorry for the duplicated report.

**Closed by ncdc** 2018-09-11 14:59 UTC
Labels: Duplicate
