### ISSUE TITLE
Introduce wildcard for deleting backups

### ISSUE THREAD

**Issue by containscafeine** [heptio/ark#441] opened 2018-04-20 07:12 UTC
Well, I have a lot of backups -

```console
$ ark backup get
NAME                      STATUS             CREATED                         EXPIRES   SELECTOR
...
...
testproj-20180418165805   FailedValidation   2018-04-18 16:58:05 +0530 IST   1d        <none>                                                     
testproj-20180418165800   FailedValidation   2018-04-18 16:58:00 +0530 IST   1d        <none>                                                     
testproj-20180418165755   FailedValidation   2018-04-18 16:57:55 +0530 IST   1d        <none>                                                     
testproj-20180418165750   FailedValidation   2018-04-18 16:57:50 +0530 IST   1d        <none>                                                     
testproj-20180418165745   FailedValidation   2018-04-18 16:57:45 +0530 IST   1d        <none>                                                     
testproj-20180418165740   FailedValidation   2018-04-18 16:57:40 +0530 IST   1d        <none>                                                     
testproj-20180418165640   FailedValidation   2018-04-18 16:56:40 +0530 IST   1d        <none>                                                     
testproj-20180418165540   FailedValidation   2018-04-18 16:55:40 +0530 IST   1d        <none>                                                     
testproj-20180418165440   FailedValidation   2018-04-18 16:54:40 +0530 IST   1d        <none>                                                     
testproj-20180418165340   FailedValidation   2018-04-18 16:53:40 +0530 IST   1d        <none>                                                     
testproj-20180418165240   FailedValidation   2018-04-18 16:52:40 +0530 IST   1d        <none>                                                     
testproj-20180418165140   FailedValidation   2018-04-18 16:51:40 +0530 IST   1d        <none>                                                     
testproj-20180418165040   FailedValidation   2018-04-18 16:50:40 +0530 IST   1d        <none>                                                     
testproj-20180418165000   FailedValidation   2018-04-18 16:50:00 +0530 IST   1d        <none>                                                     
testproj-20180418164900   FailedValidation   2018-04-18 16:49:00 +0530 IST   1d        <none>                                                     
testproj-20180418164800   FailedValidation   2018-04-18 16:48:00 +0530 IST   1d        <none>                                                     
testproj-20180418164700   FailedValidation   2018-04-18 16:47:00 +0530 IST   1d        <none>                                                     
testproj-20180418164616   FailedValidation   2018-04-18 16:46:16 +0530 IST   1d        <none>                                                     
testproj-20180418164400   FailedValidation   2018-04-18 16:44:00 +0530 IST   1d        <none>                                                     
testproj-20180418164300   FailedValidation   2018-04-18 16:43:00 +0530 IST   1d        <none>                                                     

$ ark backup get | wc -l              
223
```

I have sort of a cron job that takes all of these. I'd love to delete a lot of these using a wildcard, but -

```console
$ ark backup delete testproj-2018041816*
An error occurred: backups.ark.heptio.com "testproj-2018041816*" not found
```

It'd be awesome if I'm able to do something like that.

**Comment by ncdc** [comment] 2018-04-20 10:19
I have a WIP pull to do bulk backup deletion. I need to rebase it now that
we have DeleteBackupRequests.

**Comment by ncdc** [comment] 2018-05-10 10:58
This is a dupe of #295 - closing.

**Closed by ncdc** 2018-05-10 10:58 UTC
