### ISSUE TITLE
Restic restore fails for dynamically provisioned EFS volume

### ISSUE THREAD

**Issue by trondhindenes** [heptio/ark#572] opened 2018-06-22 10:20 UTC
After having successfully performed a restic-integrated backup, and deleting the backed-up namespace, restoring the same fails. The output from the restic pod on the host shows:
```
time="2018-06-21T22:02:50Z" level=error msg="Error getting volume directory name" controller=pod-volume-backup error="volume not found in pod" error.file="utils.go:66" error.function=GetVolumeDirectory logSource="pkg/controller/pod_volume_backup_controller.go:158" name=nginx-example-pb4kc namespace=heptio-ark
time="2018-06-22T10:15:35Z" level=error msg="Error restoring volume" controller=pod-volume-restore error="error identifying path of volume: expected one matching path, got 0" error.file="pod_volume_backup_controller.go:295" error.function=singlePathMatch logSource="pkg/controller/pod_volume_restore_controller.go:273" name=nginx-example-20180622121532-zfcj8 namespace=heptio-ark
```

Here's the full manifest of the backed up item (this was the only stuff living in the backed-up namespace):
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        backup.ark.heptio.com/backup-volumes: nginx-logs
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

**Comment by ncdc** [comment] 2018-06-22 10:21
I have a feeling this will be fixed by #569

**Comment by trondhindenes** [comment] 2018-06-22 10:34
ah, gotcha. Testing.

**Comment by trondhindenes** [comment] 2018-06-22 10:40
Hm, still not good. I'm using the "efs-provisioner" (https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs) to mount EFS-based volumes with pods. 

Just thinking out load: When I deleted the namespace (which contained the pvc), efs-provisioner essentially deletes that pvc dir inside the EFS. When I perform a restore, it's unclear to me what happens when ark recreates that pvc. I'll do another test where the pvc is kept outside of the deleted namespace, but still recreated (to zero it out) and see what happens.

**Comment by trondhindenes** [comment] 2018-06-22 10:41
log from the to-be-restored pod:
```
  Warning  FailedMount            51s   kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-r8f1b15f2ce8b4881b7a8266f85facb76.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  50s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-r0aba8a64e72d46ab84ef4b1da4d6a17c.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  49s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-r380973402f3d44c699dd3e86ad10049f.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  47s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-ra4f02e899b274aa7a43aecafb32dd0ba.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  43s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-r5eaf3439079048ed9727fbd3b5dfa3f4.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  35s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-r6fa36f9af6c94ae7b13360ba2eef7457.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
  Warning  FailedMount  19s  kubelet, ip-10-245-20-18.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 --scope -- mount -t nfs -o vers=4.1 fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 /var/lib/kubelet/pods/ea283fa7-7607-11e8-8ee2-06c9704435d0/volumes/kubernetes.io~nfs/pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0
Output: Running scope as unit run-raeb6c5bcd5144568a7e67c093704241c.scope.
mount.nfs: mounting fs-59c6a090.efs.eu-west-1.amazonaws.com:/nginx-logs-pvc-b1e26f90-7590-11e8-8ee2-06c9704435d0 failed, reason given by server: No such file or directory
```

**Comment by ncdc** [comment] 2018-06-22 10:42
Ok, must be a different root cause. I'll be back online around 9:30am EDT and we can chat more if you'd like.

**Comment by trondhindenes** [comment] 2018-06-22 10:46
thanks!

**Comment by trondhindenes** [comment] 2018-06-22 11:21
Hm, I'm not able to make it take a backup if I do more granular filtering. It's not clear to me how ark behaves i i include a deployment, but exclude the pvc used by a pod in a deployment. It's also not very easy to see the list of resources (objects) contained in a backup :thinking:

**Comment by ncdc** [comment] 2018-06-22 12:59
@trondhindenes I have a theory for why the restore fails. I'm going to spin up a test cluster to try it out.

When backing up, Ark currently automatically includes all PVCs referenced by a pod, as well as all PVs referenced by PVCs (regardless of the excluded resources setting). We may need to consider adjusting this behavior.

We have a couple of open issues related to seeing what's in a backup: #448 (which is for restores, but we might do for backups too) and #396. In the meantime, you can run `ark backup download NAME` to download the backup tarball and you'll be able to see exactly what Ark backed up.

I'll report back on my theory once I run my test.

**Comment by trondhindenes** [comment] 2018-06-22 16:05
sweet, thanks! I wanted to verify that my selector had "hit" the pod but not the pvc but couldn't find an easy way to do that. Downloading the tar works as a workaround. I would definetely be interested in a backup-scoped view of "what's in the backup".

**Comment by trondhindenes** [comment] 2018-06-22 16:56
I guess the expected behavior at restore would be to create the pvc, and then let Kubernetes' control loop "satisfy" that with a pv, which would then be mounted and restored using the restic integration.

That said, a volume can also be "static" (eg not created to respond to a pvc) so there's definetely some complexity in getting the backup restore right. Personally I wouldn't mind if there truckload of options to fine-tune ark's behavior both when backing up and restoring.

**Comment by ncdc** [comment] 2018-06-22 17:01
Yes, the issue here is what I thought - Ark recreates the PV from the backup, which points at the path in the NFS (EFS) server that no longer exists (due to it being deleted when the PVC was deleted). We'll see what we can come up with.

**Comment by trondhindenes** [comment] 2018-06-22 18:19
imho a suitable logic would be:
- if pod has volume(s), grab the list of volume (but controllable by a flag)
- if volume is created based on a pvc, backup only the pvc object, not the pv (but controllable by a flag)

I haven't worked with that many other volume "drivers" but backing up/restoring a pvc-created pv object kinda never seems like a good idea to me, as there's a big chance of doing things that the volume provisioner should get to do exclusively.

**Comment by ncdc** [comment] 2018-06-22 18:30
My plan is to skip restoring a PV if the following 2 things are true:

1. We don't have a block storage snapshot for it
1. Its reclaim policy is Delete

**Comment by trondhindenes** [comment] 2018-06-22 18:44
yup that makes sense. I have to admit I haven't worked with EBS-based volumes.

**Comment by rosskukulinski** [comment] 2018-06-24 23:19
@ncdc What's your thinking for `(2) Its reclaim policy is Delete?`  I'm wondering if explicit CLI option(s) would be better.

**Comment by ncdc** [comment] 2018-06-24 23:56
Yes, both true. If it's a dynamically provisioned PV with a reclaim policy of Delete (the default) and Ark didn't take a block snapshot, then there's no way that having Ark recreate the PV will be useful:

1. If the PV is still in the cluster, then when Ark tries to restore it, it will get an already-exists error, and it will be a no-op. There's no data loss because it's still there. We can't restore anything because we don't have a snapshot. If we have a restic backup, we'll be able to restore it.
1. If the PV is not in the cluster, then when Ark tries to restore it, it will get created successfully. However, the PV in the backup refers to some vendor-specific metadata that doesn't exist any more, because of the combination of dynamic provisioning and the Delete reclaim policy - whatever was dynamically created before has been deleted, and any PV json that says "it's NFS with path /foo" or whatever will be invalid. What you end up with is the kubelet continually attempting to attach and mount a volume that's unmountable.

**Comment by rosskukulinski** [comment] 2018-06-25 00:08
Ok! I now understand.  👍

**Comment by rosskukulinski** [comment] 2018-06-25 00:08
Putting this against v0.9.0, let me know if that doesn't make sense.

**Comment by trondhindenes** [comment] 2018-06-26 00:57
I'd be happy to test a prerelease build in my env

**Comment by ncdc** [comment] 2018-06-26 01:23
Ok great. I can get you an image tomorrow morning.

**Comment by ncdc** [comment] 2018-06-26 11:09
@trondhindenes I just pushed `gcr.io/andy-heptio/ark:restic-efs-test` and `gcr.io/andy-heptio/ark-restic-restore-helper:restic-efs-test`. You should be able to use the same `ark` command line client you currently have. Let me know how it goes!

**Comment by trondhindenes** [comment] 2018-06-26 13:00
sweet, will do!

**Comment by trondhindenes** [comment] 2018-06-26 13:03
hm, how do I use the ark-restic-restore-helper image? I've updated both the ark pod and the restic daemonset pods to use the `gcr.io/andy-heptio/ark:restic-efs-test` image.

**Comment by ncdc** [comment] 2018-06-26 13:10
Heh that was probably more information than you needed :-) Ark will automatically pick it up as the image to use in the pod init containers when restoring - you won't need to do anything.

**Comment by trondhindenes** [comment] 2018-06-26 13:29
good to know :-) thanks! will try and do some testing today.

**Comment by trondhindenes** [comment] 2018-06-26 20:14
hm, I'm getting a new strange error while performing the backup operation:
```
time="2018-06-26T20:10:15Z" level=info msg="Backup completed with errors: restic repository not found: resticrepository.ark.heptio.com \"nginx-example2\" not found" backup=heptio-ark/nginx-backup3 logSource="pkg/backup/backup.go:301"
```
Exact same config/operation as before (this worked on the release version of ark)

**Closed** 2018-06-26 20:52 UTC
Labels: Bug
